### ISSUE TITLE
Build instructions don't quite work

### ISSUE THREAD

**Issue by stevage** [DDKnoll/SVGeneration#3]
There's no step to install Grunt. So either the user should `npm install -g grunt` first (which version?), or they need to run it explicitly somehow (`node_modules/grunt/...?`)

I did the first, and ran `npm start`. It seemed to build and run a server ok, but what's served at `localhost:3003` is just the default BrowserSync page. Not sure how to get it to serve up the contents of `dist` (I'm not very familiar with Grunt or BrowserSync).

**Comment by DDKnoll** [comment]
Just updated the Readme.  You just need to go to localhost:3131 to see the actual hosted site.

**Comment by stevage** [comment]
Thanks, that works.
